### ISSUE TITLE
LoadError: cannot load such file -- octopress-debugger

### ISSUE THREAD

**Issue by maiertech** [octopress/debugger#1]
I include `octopress-debugger` via the `Gemfile` in a Jekyll project running Jekyll `3.0.0.pre.beta7`. When I use Ruby 2.1.5, no issue, everything works just fine. When I switch to Ruby 2.2.1 (via RVM), I get the following error:

```
Configuration file: /Users/thilo/Repositories/mdotasia-theme/test/source/_config.yml
Resolving dependencies...
rake aborted!
LoadError: cannot load such file -- octopress-debugger
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/plugin_manager.rb:30:in `require'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/plugin_manager.rb:27:in `each'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/plugin_manager.rb:27:in `require_gems'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:98:in `setup'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:49:in `initialize'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/commands/build.rb:30:in `new'
/Users/thilo/.rvm/gems/ruby-2.2.1@mdotasia-theme/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/commands/build.rb:30:in `process'
/Users/thilo/Repositories/mdotasia-theme/lib/tasks/build.rake:74:in `block (2 levels) in <top (required)>'
/Users/thilo/Repositories/mdotasia-theme/lib/tasks/build.rake:82:in `block (2 levels) in <top (required)>'
Tasks: TOP => site:build
(See full trace by running task with --trace)
```

**Comment by sckott** [comment]
Same problem for me, using Jekyll `2.5.1` and Ruby `2.2.3p173`

**Comment by NathanHazout** [comment]
I did `gem install octopress-debugger`

My config:

```
baseurl: /NATHANH
permalink: pretty
exclude: [old-backup]
gems:
  - jekyll-redirect-from
  - octopress-debugger
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
```

The result:

```
Configuration file: /Users/nathanh/Git/nathanh.github.ibm.com/_config.yml
/Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `require': cannot load such file -- octopress-debugger (LoadError)
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/nathanh/.gem/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/nathanh/.gem/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
    from /Users/nathanh/.gem/bin/jekyll:23:in `load'
    from /Users/nathanh/.gem/bin/jekyll:23:in `<main>'
localhost:nathanh.github.ibm.com nathanh$ 
```
